# Generated by Django 6.0.6 on 2026-08-21 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_remove_submission_nano'),
        ('nano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NanoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nano_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='nano.nanofolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NanoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('richtext', 'Rich Text'), ('code', 'Code')], default='richtext', max_length=10)),
                ('language', models.CharField(choices=[('plaintext', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('bash', 'Bash'), ('sql', 'SQL'), ('markdown', 'Markdown')], default='plaintext', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nano_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nano.nanofolder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Nano',
        ),
    ]
