# Generated by Django 6.0.6 on 2026-08-17 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='workspace.workspacefolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('richtext', 'Rich Text'), ('code', 'Code')], default='richtext', max_length=10)),
                ('language', models.CharField(choices=[('plaintext', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('bash', 'Bash'), ('sql', 'SQL'), ('markdown', 'Markdown')], default='plaintext', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace.workspacefolder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
