# Generated by Django 6.0.6 on 2026-08-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='nano',
        ),
    ]
