# Generated by Django 6.0.6 on 2026-08-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_remove_submission_nano'),
        ('nano', '0002_nanofolder_nanofile_delete_nano'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='nano_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_submissions', to='nano.nanofile'),
        ),
    ]
